apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pwachart.fullname" . }}
  labels:
    {{- include "pwachart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "pwachart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pwachart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pwachart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "pwachart.fullname" . }}
          {{- if .Values.app.probes.http.enabled }}   
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.http.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.probes.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.http.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.http.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.probes.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.http.periodSeconds }}
          {{- end}}
          {{- if .Values.app.probes.tcp.enabled }}   
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.app.probes.tcp.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.tcp.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.app.probes.tcp.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.tcp.periodSeconds }}
          {{- end}}
          {{- if .Values.app.probes.exec.enabled }}   
          livenessProbe:
            exec:
              command: {{- range .Values.app.probes.exec.command }}
                - {{.}}
                {{ end }}
          readinessProbe:
            exec:
              command: {{- range .Values.app.probes.exec.command }}
                - {{.}}
                {{ end }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
